# Generated by Django 5.1.4 on 2024-12-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_task_assigned_attendee_alter_task_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
