# Generated by Django 5.1.4 on 2024-12-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='assigned_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_attendees', to='event_app.event'),
        ),
    ]
