# Generated by Django 5.1.4 on 2024-12-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_attendee_assigned_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
